default_step_num: 2
default_step_length: 0.2
default_side_step_length: 0.05
default_step_angle_radian: 0.1
default_step_time: 2
expanded_step_num: 1
expanded_step_length: 0.1
expanded_side_step_length: 0.05
expanded_step_angle_radian: 0.3
expanded_step_time: 2
centered_step_num: 1
centered_step_length: 0.05
centered_side_step_length: 0.1
centered_step_angle_radian: 0.3
centered_step_time: 2
turn_step_num: 1
turn_step_length: 0
turn_side_step_length: 0.05
turn_step_angle_radian: 0.3
turn_step_time: 2