default_step_num: 4
default_step_length: 0.18
default_side_step_length: 0.1
default_step_angle_radian: 0.05
default_step_time: 0.85
expanded_step_num: 4
expanded_step_length: 0.12
expanded_side_step_length: 0.07
expanded_step_angle_radian: 0.3
expanded_step_time: 0.85
centered_step_num: 4
centered_step_length: 0.05
centered_side_step_length: 0.1
centered_step_angle_radian: 0.3
centered_step_time: 0.85
turn_step_num: 4
turn_step_length: -0.01
turn_side_step_length: 0.05
turn_step_angle_radian: 0.3
turn_step_time: 0.85
