default_step_num: 3
default_step_length: 0.20
default_side_step_length: 0.06
default_step_angle_radian: 0.05
default_step_time: 0.85
expanded_step_num: 3
expanded_step_length: 0.09
expanded_side_step_length: 0.07
expanded_step_angle_radian: 0.173333
expanded_step_time: 0.85
centered_step_num: 3
centered_step_length: 0.015
centered_side_step_length: 0.06
centered_step_angle_radian: 0.52
centered_step_time: 0.85
turn_step_num: 3
turn_step_length: -0.01
turn_side_step_length: 0.07
turn_step_angle_radian: 0.52
turn_step_time: 0.85
