default_step_num: 2
default_step_length: 0.15
default_side_step_length: 0.05
default_step_angle_radian: 0.3
default_step_time: 2
expanded_step_num: 1
expanded_step_length: 0.1
expanded_side_step_length: 0.05
expanded_step_angle_radian: 0.3
expanded_step_time: 2
centered_step_num: 1
centered_step_length: 0.05
centered_side_step_length: 0.1
centered_step_angle_radian: 0.45
centered_step_time: 2
foot_step_dsp: 0.4
foot_step_foot_z_swap: 0.06
foot_step_body_z_swap: 0
foot_step_y_zmp_conv: -0.03
